### ISSUE TITLE
Adding Trackables from device storage folder, not from assets folder

### ISSUE THREAD

**Issue by kanoe92** [artoolkitx/artoolkitx#126]
I've seen AR2DTrackingExample for Android and I'm wondering if is possible to add Trackables from different folder than assets? 

`int track = ARController.getInstance().addTrackable("2d;Data/" + trackable.getName() + ";" + trackable.getWidth());`

Is it possible to provide path to image file in storage instead of `"Data/" + trackable.getName()` with saved pattern 
`2d;{path};{trackableWidth}`?

I've tried to do this, but I'm getting `track = -1` so I believe this number says that it is impossible to add this trackable. Is it because files from device storage are not cached?

Any help will be appreciated, thanks.

**Comment by philip-lamb** [comment]
The call to addTrackable with type 2d (i.e. a 2D texture image) eventually finds its way to https://github.com/artoolkitx/artoolkitx/blob/master/Source/ARX/ARTrackable2d.cpp#L67 which calls the image loader. It just takes the path you pass it. In most of the examples, this path is formed by appending the file name to the path inside the cache folder, where the cache folder is set up by unpacking from the app package.

However there's no reason why you can't just supply it any valid and accessible path in the native filesystem. Note that an Android app has only limited access to the filesystem because of app sandboxing, but if you've fetched a jpeg, written it to a file, and want to use it as a tracking target, this should be trivial.

Make sure you use absolute pathnames, since Android doesn't really let you set the current working directory.
