### ISSUE TITLE
missing build.sh

### ISSUE THREAD

**Issue by micrem73** [artoolkitx/artoolkitx#26]
In readme is told:

* To rebuild the SDK and examples for macOS, in Terminal navigate to `Source` and execute the command `./build.sh macos examples`

but no build.sh file is present.

**Comment by ThorstenBux** [comment]
https://github.com/artoolkitx/artoolkitx/blob/master/Source/build.sh

Where are you looking for it?

**Comment by micrem73** [comment]
I downloaded from download section of artoolkitx.org the file https://github.com/artoolkitx/artoolkitx/releases/download/1.0.1/artoolkitX.for.macOS.v1.0.1.dmg

**Comment by ThorstenBux** [comment]
Well, if you download the versions we already build then you won't find a build.sh file. I'm almost certain you won't find any Source directory either because we don't ship the built packages including sources. If you would like to build artoolkitX by yourself you need to clone the git repository from here:
```git clone https://github.com/artoolkitx/artoolkitx.git```

Cheers
