### ISSUE TITLE
Changing source on Android

### ISSUE THREAD

**Issue by nickos64252** [artoolkitx/artoolkitx#70]
Hello,

I want to change the video source on android (ie: getting another camera, in my case, it will be an external one but, for now, I just want the front or rear camera).
I added "-source=1" (without quotes) for StartRunning in ARController but the back camera is always the active camera. (I tried other number than 1)

I tried passing width and height too without success. 
When I pass -format=0 nothing happen, but with -format=RGBA the app crashes.

Why source, width and height aren't processed ?

Thank you

**Comment by philip-lamb** [comment]
On Android, the video config parameters can basically be considered internal to artoolkitX. Since the Android Camera2 Java framework controls the camera, you should make changes in which camera is active using the CameraPreferences activity, or similar. If you want to change the format of the video frames, the format change should also be on the Java side. The -format+RGBA controls whether multi-planar formats are converted to RGBA, and is only implemented for Android's NV21/NV12 and YUV_420_888 formats.
