### ISSUE TITLE
Artoolkitx 32Bits

### ISSUE THREAD

**Issue by robertinonicolazzi** [artoolkitx/artoolkitx#87]
Hello friend, well like the title says

there is a way to run artoolkitx on a 32 bits machine??

Thanks!

**Comment by philip-lamb** [comment]
Which OS?

**Comment by robertinonicolazzi** [comment]
> Which OS?

Sorry philip, i forgot. Im using Elementary Os, which is ubuntu based. Thanks a lot

**Comment by philip-lamb** [comment]
It is possible (e.g. Raspbian 32-bit is supported) but not currently supported. You'd need to ensure you've got the required packages. Particularly, if you want to use the 2D texture tracker, you'll need OpenCV 3.x on the system. Otherwise you'll just have the square and legacy NFT trackers available.

Before anything else, you'd need to modify https://github.com/artoolkitx/artoolkitx/blob/master/Source/CMakeLists.txt#L201 to insert a new platform variant `elseif ("${ARX_TARGET_PLATFORM_VARIANT}" STREQUAL "elementaryos")` and define the preprocessor flags similar to the other Linux platforms. Then you could create your own build directory and run cmake with that parameter e.g. `cmake .. -DARX_TARGET_PLATFORM_VARIANT=elementaryos -DCMAKE_BUILD_TYPE=Debug`

**Comment by robertinonicolazzi** [comment]
well philips. thanks a lot. I succesfully run my app with artoolkitx just compiled with regular Linux platform target without changing any setting from the original Cmake

Thanks a lot!
